---
- name: Configure Web Servers host
  hosts: web


  vars_files:
    - ../vars/main.yml


  roles:
    - role: packages_install
      packages_install_list: "{{ default_packages_to_install }}"
      become: true
    - role: hifis.unattended_upgrades
      unattended_automatic_reboot_time: 04:00  # noqa: var-naming[no-role-prefix]
      become: true
    - role: geerlingguy.security
      security_ssh_port: "22"
      become: true
    - role: geerlingguy.docker
      become: true


  tasks:
    - name: Setup cron to clean docker images
      ansible.builtin.cron:
        name: "Clean docker images"
        minute: "0"
        hour: "3"
        job: "docker system prune -a -f"
        cron_file: "clean_docker_images"
        user: root
      become: true

  - name: Setup web servers
    # TODO: add web servers
